### ISSUE TITLE
dayjs Time comparison(past/present/future)

### ISSUE THREAD

**Issue by CodrinCarpovici** [CodrinCarpovici/trimtutor#31]
Update calendar to current day at the the top
Generate another 6 days after current day
Make use of data-date attribute and store exact date DD/MM/YYYY to use for local Storage

**Comment by D-Tsonev** [comment]
The table is created dynamically.
The current day of the week is on top. and highlighted in Yellow
Both cells ( day of the week and + button are storing the date in DD/MM/YYYY format
